[TS] Disable scrolling to the top of the page when the post modal opens
okuda-seminar/Twitter-Clone pull request #506
Opened 2024-11-19 14:19 UTC by ryuju0911

## Issue Number
#500 

## Implementation Summary
This PR prevents the page from scrolling to the top when the post modal opens by using the `Link` component provided by Next.js. It offers useful features, such as controlling scroll behavior. One notable advantage is its ability to automatically prefetch routes when they become visible in the user's viewport (this functionality is only available in production mode).
Additionally, we can integrate Chakra UI's `Link` component with Next.js by passing the `as={NextLink}` property.

As the original X does not display the post button for users who are not logged in, I removed the login prompt modal.

## Scope of Impact
- Usability of the post modal

## Particular points to check
Please confirm that the page does not scroll to the top when the post modal opens.

## Test
Nothing added.

## Schedule
11/22

## References
- [\<Link\>](https://nextjs.org/docs/pages/api-reference/components/link)
- [2-prefetching](https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#2-prefetching)
- [usage with Next.js](https://v2.chakra-ui.com/docs/components/link/usage#usage-with-nextjs9)

2024-11-22 07:38 UTC, a-shigemichi requested changes

2024-11-22 07:38 UTC, a-shigemichi commented on ts/twitter/src/lib/components/sidebar-post-button.tsx
> +      <Box>
Could you explain the reason for using double Box wrappers?

2024-11-23 03:13 UTC, ryuju0911 commented on ts/twitter/src/lib/components/sidebar-post-button.tsx
> +      <Box>
@a-shigemichi 
Thank you for pointing that out. I overlooked it...
Please check it again.

2024-11-23 03:34 UTC, a-shigemichi approved these changes
LGTM

2024-11-26 11:23 UTC, ryuji0123 approved these changes

2024-11-26 11:37 UTC, merged