[TS] Implement Loading and Error Pages for Data Fetching States
okuda-seminar/Twitter-Clone pull request #508
Opened 2024-11-21 01:57 UTC by a-shigemichi

## Issue Number
https://github.com/okuda-seminar/Twitter-Clone/issues/472

## Implementation Summary
Added error.tsx file, which follows the official Next.js code conventions. Additionally, removed error rendering and useEffect from my-profile.tsx.

## Particular points to check
Please verify that `error.tsx` is rendered when fetch errors occur on the /profile route by testing different scenarios such as changing the endpoint or username.

## Reference

https://github.com/user-attachments/assets/7e4856d9-f4d8-4e23-b5d8-4736305d0a65

## Test
I was unable to implement manual mocks properly, and therefore could not write the tests scheduled for this week.

## Schedule
2024/11/22

2024-11-21 05:14 UTC, TakayaShirai requested changes
@ryuju0911
In addition to the requested changes, I found that `React.FC` is not compatible with async components when I discussed with ChatGPT. This seems tricky for me to review properly, so I'd appreciate it if you could review this part after I finish my review.

2024-11-21 05:59 UTC, a-shigemichi commented on ts/twitter/src/app/error.tsx
> +export default function Error({
error.tsx is a component that gets called when an error is thrown and is never imported directly. I believe using export default is appropriate, similar to page.tsx.

2024-11-21 06:38 UTC, TakayaShirai approved these changes
LGTM. However, please ensure that outdated conversations are resolved once the new commit is pushed

2024-11-21 12:51 UTC, ryuju0911 approved these changes
LGTM

2024-11-21 12:53 UTC, ryuju0911 commented
@TakayaShirai 
`React.FC` now works with React Server Components and async components. Perhaps ChatGPT provided outdated information.

2024-11-21 13:12 UTC, ryuji0123 commented
Why not checking official doc or any articles? I've never seen referring to LLM as a primary resource.

2024-11-21 13:17 UTC, ryuji0123 commented
In case React.FC is incompatible with async components, shouldn't this commit crash the app? I'm not sure why @TakayaShirai pointed out...

2024-11-21 13:22 UTC, ryuji0123 approved these changes

2024-11-21 13:22 UTC, ryuji0123 commented on ts/twitter/src/app/error.tsx
> +    console.error(error);
BTW, it's great if we can accumulate error in logging platform to evaluate the reliability of our app. Let's talk more on Saturday.

2024-11-21 13:23 UTC, ryuji0123 commented on ts/twitter/src/app/error.tsx
> +    console.error(error);
@a-shigemichi 

You can mark this thread resolved once you've checked. In that case, it's common to comment "ACK".

2024-11-21 13:23 UTC, merged

2024-11-21 22:58 UTC, TakayaShirai commented
I'm sorry for causing any confusion with this avoidable mistake. I should have noticed that crash would occur if my statement were correct and that it is compatible with async components earlier, even though I reviewed the documentation. I'll make sure to look into details more carefully moving forward. Thank you for pointing this out.

2024-11-22 09:05 UTC, a-shigemichi commented on ts/twitter/src/app/error.tsx
> +    console.error(error);
ACK