[iOS] Remove DrawerPresentation Library and Implement Simple Transition
okuda-seminar/Twitter-Clone pull request #512
Opened 2024-11-25 23:30 UTC by TakayaShirai

## Issue Number
https://github.com/okuda-seminar/Twitter-Clone/issues/502

## Implementation Summary
This PR removes the "DrawerPresentation" package from the project and integrates a new custom side menu transition animation.

## Scope of Impact
When users tap the icon button in the top-left corner, the new transition animation will display the side menu. Also, the side menu dismisses when users tap a button within it, transitioning to the corresponding new view.

## Particular points to check
Please check if the implemented new transition animation works properly.

## Reference
https://github.com/user-attachments/assets/70d38d30-e92f-4391-a0d3-07d88e132cc4

## Schedule
Until 11/30.

2024-11-27 06:10 UTC, a-shigemichi approved these changes
LGTM

2024-11-28 10:40 UTC, ryuji0123 requested changes

2024-11-28 10:40 UTC, ryuji0123 commented on swift/Twitter-iOS/Twitter-iOS/SideMenuTransition/SideMenuTransitionAnimator.swift
> +import UIKit
This can be changed in the future, but let's re-organize the directory tree like:

```
Twitter-iOS/
- Root/
  - AppDelegate
  - SceneDelegate
  - AppRootViewController
  - MainRootViewController
  - SideMenu/
    - SideMenuTransitionAnimator
    - SideMenuTransitionController
    - SideMenuView
- Features/
- SDK/
...
```

2024-11-28 23:43 UTC, ryuji0123 commented on swift/Twitter-iOS/Twitter-iOS/SideMenuTransition/SideMenuTransitionAnimator.swift
> +import UIKit
Check my above comment very carefully.

2024-11-28 23:45 UTC, ryuji0123 requested changes
I wanted you to work carefully to save my time.

2024-11-29 00:06 UTC, TakayaShirai commented
I apologize for taking up your time. I should have been more careful in reading the comments.

2024-11-29 14:05 UTC, ryuji0123 approved these changes

2024-11-29 14:05 UTC, merged

2024-11-29 14:07 UTC, ryuji0123 commented
Yeah, I don't memorize how many times I asked you to work carefully...
Especially this time, even though I clearly showed the exact required change, you missed it. It was really surprising to me in a bad way.

2024-11-29 14:13 UTC, ryuji0123 commented
Reflecting what your mentor pointed out is definitely necessary skill as a junior engineer. If I were your mentor in a company, unfortunately I should report I must very carefully check all of your actions in detail as you can easily make mistakes. This is a really bad signal when evaluating your performance. 

Given that we must confirm things are going well before launching features in prod, your manager cannot choose you as a main engineer without such skills and in that case, you might need to work impact less tasks...

2024-11-29 20:43 UTC, TakayaShirai commented
I appreciate your thoughtful feedback.

First, I sincerely apologize for overlooking the comments despite your repeated reminders. The fact that I have not yet been able to improve on such an essential skill as a junior engineer is a serious issue, and I will ensure that this does not happen again in the future.

Although I have been trying to be cautious and have made efforts to double-check my work, I've noticed that these kinds of mistakes tend to occur especially when I’m pressed for time. May I ask for if there are any specific strategies or practices you personally use to prevent such errors? I would greatly appreciate your advice to help me improve.

2024-11-30 02:58 UTC, ryuji0123 commented
I don't think we have a silver bullet. As God is in the details, you need to act carefully and keep in mind that it's your responsibility to make sure your work is enough quality.

2024-11-30 07:18 UTC, TakayaShirai commented
Thank you for your advice.

To be honest, if possible, I would like to use the university as an excuse, but I believe I cannot, considering that there are many other junior engineers able to avoid these kinds of mistakes even now, let alone in a professional environment. I will act carefully, keep my responsibilities in mind, and focus on improving my skills as a junior engineer to avoid wasting your time.

2024-11-30 09:04 UTC, ryuji0123 commented
To clarify, I didn't point out you're busy with the university tasks. I meant I'm thinking studying universities is not a good way to be ready for becoming a good software engineer. At least in our university, professors are definitely not good at teaching students as students are not learning enough skills at laboratories.