[TS] Implement Server Sent Events in timeline feed using EventSource
okuda-seminar/Twitter-Clone pull request #513
Opened 2024-11-26 08:11 UTC by a-shigemichi

## Issue Number
https://github.com/okuda-seminar/Twitter-Clone/issues/505

## Implementation Summary
Implemented Server-Sent Events (SSE) using EventSource. Since error messages from SSE are received asynchronously and cannot be caught by error.tsx, I created a dedicated error UI component within timeline-feed.tsx to handle these errors appropriately.

## Particular points to check
Please verify if the error handling implementation is appropriate. 

## Test
`src/app/home/_components/timeline/__test__/timeline-feed.spec.tsx`
1. Start the frontend server (in the Twitter-Clone directory)
```
$ docker compose up -d
```
2. Enter the application container and run all test files
```
$ docker compose exec app bash
$ yarn test
```
　Use `--coverage` flag to generate coverage report

## Schedule
11/29

2024-11-27 08:09 UTC, TakayaShirai requested changes
I couldn't reproduce the referenced video, and the timeline didn’t update automatically after posting. I also noticed some errors in the Google Chrome console. Could you investigate this issue and let me know if I might have followed the wrong steps?

https://github.com/user-attachments/assets/661fbbf3-c606-44be-82c8-ef0ee24fe8d0

2024-11-27 14:23 UTC, a-shigemichi commented
> I couldn't reproduce the referenced video, and the timeline didn’t update automatically after posting. I also noticed some errors in the Google Chrome console. Could you investigate this issue and let me know if I might have followed the wrong steps?
> 
>  Screen.Recording.2024-11-26.at.11.37.25.PM.mov

Due to the implementation of the delete feature in the x-clone-backend repository, it appears that the API schema has been modified. We will add a TODO to resolve this issue in the future. For this review, please check the implementation using the x-clone-backend repository before the delete feature implementation by checking out 
`git checkout 302d1a3ba1dde9f5d1400785052b409cbf06ba83`.
I have noted the same considerations in the 'Review Considerations' section as well.

2024-11-27 22:53 UTC, TakayaShirai approved these changes
LGTM

2024-11-29 12:08 UTC, ryuju0911 requested changes

2024-11-29 12:08 UTC, ryuju0911 commented on ts/twitter/src/app/home/_components/timeline/__test__/timeline-feed.spec.tsx
> +      removeEventListener: jest.fn(),
They are not used.

2024-11-29 12:08 UTC, ryuju0911 commented on ts/twitter/src/app/home/_components/timeline/__test__/timeline-feed.spec.tsx
> +    };
Why did you mutate the `process.env`? It is irrelevant to this test.

2024-11-30 08:09 UTC, ryuju0911 approved these changes
LGTM

2024-11-30 13:44 UTC, ryuji0123 commented on ts/twitter/src/app/home/_components/timeline/use-timeline-feed.ts
> +  posts: GetCollectionOfPostsBySpecificUserAndUsersTheyFollowResponse;
IIUC `GetCollectionOfPostsBySpecificUserAndUsersTheyFollowResponse` contains posts for a specific user's "Following" tab. In prod, it looks like Following tab shows three kinds of posts:
1. Posts by a login user
2. Posts by users followed by the login user
3. Ads posts

and this could change in the future. I guess including all info in request / response names is a bit reduntant and `GetCollectionOfPostsBySpecificUserAndUsersTheyFollowResponse ` looks still a bit unclear. So why not changing like:
- `GetCollectionOfPostsBySpecificUserAndUsersTheyFollowRequest` -> `FollowingPostsRequest`
- `GetCollectionOfPostsBySpecificUserAndUsersTheyFollowResponse` -> `FollowingPostsResponse`
- `getCollectionOfPostsBySpecificUserAndUsersTheyFollow` -> `fetchFollowingPosts`
and write method / class documentations as comments to indicate what kind of posts will be included?
Of course if we need another method for multiple users' Following and differentiate similar methods, then we can explicitly append `ForSpecificUser` like  `fetchFollowingPostsForSpecificUser`, but right now, it looks like optional to me.

2024-11-30 13:56 UTC, ryuji0123 requested changes

2024-11-30 13:56 UTC, ryuji0123 commented on ts/twitter/src/app/home/_components/timeline/__test__/timeline-feed.spec.tsx
> +      messageHandler({ data: "invalid json data{]" });
Shouldn't `invalid json data{]` be `invalid json data {}`?

2024-12-01 08:43 UTC, a-shigemichi commented on ts/twitter/src/app/home/_components/timeline/use-timeline-feed.ts
> +  posts: GetCollectionOfPostsBySpecificUserAndUsersTheyFollowResponse;
You're right - at this stage where there are no similar methods, there was no need for such a long name like GetCollectionOfPostsBySpecificUserAndUsersTheyFollowResponse. As you suggested, I'll change it to a more concise name and add comments to describe what kind of data is included.

2024-12-02 11:17 UTC, ryuji0123 requested changes

2024-12-02 11:17 UTC, ryuji0123 commented on ts/twitter/src/lib/actions/get-collection-of-posts-by-specific-user-and-users-they-follow.ts
>  "use server";
Why not changing this file's name to align it with its method?

2024-12-02 13:06 UTC, a-shigemichi commented on ts/twitter/src/lib/actions/get-collection-of-posts-by-specific-user-and-users-they-follow.ts
>  "use server";
I should have changed the file name along with the method.

2024-12-02 14:18 UTC, ryuji0123 requested changes

2024-12-02 14:18 UTC, ryuji0123 commented on ts/twitter/src/lib/actions/fetch-following-posts.ts
> + * - Posts by users they follow
Shouldn't `Posts by users they follow` be `Posts by users the logged-in user follows`?

2024-12-02 23:49 UTC, ryuji0123 approved these changes

2024-12-02 23:49 UTC, merged