[iOS] Implement Tap Gesture on OverlayView to Dismiss Side Menu
okuda-seminar/Twitter-Clone pull request #520
Opened 2024-12-02 03:12 UTC by TakayaShirai

## Issue Number
https://github.com/okuda-seminar/Twitter-Clone/issues/509

## Implementation Summary
This PR introduces a tap gesture recognizer to the dimming view (formerly defined as the overlay view), enabling the tap-to-dismiss functionality for the side menu.

## Scope of Impact
When users tap the dimming view, the side menu will be dismissed.

## Particular points to check
Please check if the naming conventions in `DimmingView` are aligned with the intended functionalities.

## Reference
https://github.com/user-attachments/assets/3d3785ae-d6ca-4447-86bd-0f8f802f3676

## Schedule
Until 12/7.

2024-12-03 11:35 UTC, a-shigemichi reviewed
When pressing the settings button from the home screen, it transitions to a screen like in the video, but there is no way to return to the home screen. I believe we should fix the issue where users need to quit the app to return to the previous screen.
I checked the TimelineSettingsViewController.swift but couldn't find any TODO addressing this issue.
While this is not related to the PR, please add it as a TODO.

2024-12-03 11:39 UTC, a-shigemichi approved these changes
Separately from my previous comment, regarding this PR, LGTM.

2024-12-04 04:00 UTC, TakayaShirai commented
@a-shigemichi 
Thank you for your review. I'll add a TODO later.

@ryuji0123 
Is it okay to modify the code after a review request has already been sent to someone? I'm considering updating the code soon if it's allowed. If not, I plan to make the changes in this PR if there are any additional change requests. If there aren't, I'll add the TODO in the next PR.

2024-12-04 10:17 UTC, ryuji0123 commented
@TakayaShirai 
That's fine. In case it takes you some time to change code, you can temporary remove reviewers until code is ready for review.

2024-12-04 10:38 UTC, ryuji0123 requested changes

2024-12-04 10:38 UTC, ryuji0123 commented on swift/Twitter-iOS/Twitter-iOS/Root/SideMenu/SideMenuTransitionController.swift
> +    animator.dimmingViewDidReceiveTap = { [weak presented] in presented?.dismiss(animated: true) }
dimmingViewDidReceiveTap -> dimmingViewTapAction

2024-12-04 10:38 UTC, ryuji0123 commented on swift/Twitter-iOS/Twitter-iOS/Root/SideMenu/SideMenuTransitionAnimator.swift
> -      completion: { finished in
Naming of finished & completed looks clear enough and concise to me. Do we have a strong reason for renaming?

2024-12-04 10:38 UTC, ryuji0123 commented on swift/Twitter-iOS/Twitter-iOS/Root/SideMenu/DimmingView.swift
> +  private func addTapGesture() {
It's weird to have a custom registration method like this in UIView. Use Apple's [API](https://developer.apple.com/documentation/uikit/uiview/addinteraction(_:)).

2024-12-04 10:38 UTC, ryuji0123 commented on swift/Twitter-iOS/Twitter-iOS/Root/SideMenu/DimmingView.swift
> +    alpha = 0.0
Transparent dimming view is confusing. Alpha should be initialized as an expected value like 0.5 or this view shouldn't control its own alpha and should delegate VC to do it.

2024-12-05 10:48 UTC, TakayaShirai commented on swift/Twitter-iOS/Twitter-iOS/Root/SideMenu/SideMenuTransitionAnimator.swift
> -      completion: { finished in
I personally felt that adding 'is' at the beginning was slightly better, but there are no strong reasons behind the renaming, so I’ve renamed them back.

2024-12-05 10:58 UTC, TakayaShirai commented on swift/Twitter-iOS/Twitter-iOS/Root/SideMenu/DimmingView.swift
> +  private func addTapGesture() {
I removed the `DimmingView` class to shift the responsibility of adding the tap gesture away from the `UIView` itself. Additionally, I couldn’t find out how to use the `addInteraction` [API](https://developer.apple.com/documentation/uikit/uiview/addinteraction(_:)) in this scenario, so I did not include it in this commit. If `addGestureRecognizer` is not suitable for this situation, I’d appreciate any guidance or suggestions.

2024-12-05 11:05 UTC, TakayaShirai commented on swift/Twitter-iOS/Twitter-iOS/Root/SideMenu/DimmingView.swift
> +    alpha = 0.0
I removed the `DimmingView` class and adjusted the code so that the `dimmingView`'s alpha is changed within the presentation and dismissal animations.

2024-12-06 09:52 UTC, ryuji0123 commented on swift/Twitter-iOS/Twitter-iOS/Root/SideMenu/DimmingView.swift
> +  private func addTapGesture() {
I found DrawerPresentation is using addInteraction [here](https://github.com/noppefoxwolf/DrawerPresentation/blob/main/Sources/DrawerPresentation/DrawerTransitionAnimator.swift#L16), but as `addGestureRecognizer` should also work.

2024-12-06 09:53 UTC, ryuji0123 approved these changes

2024-12-06 09:53 UTC, merged