[TS] Implement notifications UI at notifications page
okuda-seminar/Twitter-Clone pull request #521
Opened 2024-12-04 03:41 UTC by a-shigemichi

## Issue Number
https://github.com/okuda-seminar/Twitter-Clone/issues/517

## Implementation Summary
I implemented the notifications page. It displays a page indicating there are no notifications.
The implementation for when notifications exist is not included in this PR.

## References

https://github.com/user-attachments/assets/660a70e7-91e1-4ff6-b08f-e8604a633b53

## Test
`src/app/home/__test__/notifications.spec.tsx`
1. Start the frontend server (in the Twitter-Clone directory)
```
$ docker compose up -d
```
2. Enter the application container and run all test files
```
$ docker compose exec app bash
$ yarn test
```
　Use `--coverage` flag to generate coverage report

## Schedule
2024/12/6

2024-12-04 06:33 UTC, TakayaShirai requested changes

2024-12-04 06:33 UTC, TakayaShirai commented on ts/twitter/src/lib/components/setting-button.tsx
> +export const SettingButton: React.FC<Props> = (props) => {
Let's rename 'SettingButton' to 'SettingsButton'. Please make sure to also rename the file.

```suggestion
export const SettingsButton: React.FC<Props> = (props) => {
```

2024-12-04 06:33 UTC, TakayaShirai commented on ts/twitter/src/app/notifications/_components/notifications.tsx
> +          ariaLabel={"setting"}
Let's change 'setting' to 'settings' since 'settings' is used in the actual X and sounds more natural.

Reference: the settings button in the actual X, placed in the upper middle right of the view.
![Screenshot 2024-12-03 at 10 10 26 PM (2)](https://github.com/user-attachments/assets/5af54359-baef-4416-8f53-4db92eaa6161)

```suggestion
          tooltipText={"settings"}
          ariaLabel={"settings"}
```

2024-12-04 08:07 UTC, TakayaShirai commented
@ryuju0911 @a-shigemichi 

I've noticed that the same mistakes I mentioned earlier (changing 'success' to 'succeed', please refer to the first outdated comment) also appear in the `home.spec.tsx` and `post-modal.spec.tsx` files. Although Mr. Shigemichi has already made the change in `home.spec.tsx` in this PR, I think it would be better to create a separate issue and address the issues in the two files in a different PR for a cleaner commit history. However, I'm not sure whether it’s better to create a new issue or address them in this PR. I'd appreciate your thoughts on this.

2024-12-05 03:49 UTC, a-shigemichi commented
Indeed, the current approach might make the commit history messy. Instead of addressing it in this PR, I'll create a separate issue to handle it.

2024-12-05 06:29 UTC, TakayaShirai requested changes

2024-12-05 06:29 UTC, TakayaShirai commented on ts/twitter/src/app/home/__test__/home.spec.tsx
> +  // - Fix test descriptions in home.spec.tsx and post-modal.tsx.
nit: Let's move the TODO comment to above the issue point.

```suggestion
  // TODO: https://github.com/okuda-seminar/Twitter-Clone/issues/522
  // - Fix test descriptions in home.spec.tsx and post-modal.tsx.
  test("Rendering Home should success", () => {
```

2024-12-05 06:29 UTC, TakayaShirai commented on ts/twitter/src/lib/components/settings-button.tsx
> +        aria-label="settings"
I mistakenly requested the wrong changes in the previous review. The correct term, as it appears in the actual X, is 'Settings', not 'settings.' Please rename 'settings' to 'Settings.' Apologies for the confusion.

```suggestion
    <Tooltip label="Settings" placement="bottom" size="sm">
      <IconButton
        bg="transparent"
        aria-label="Settings"
```

2024-12-05 06:32 UTC, a-shigemichi commented on ts/twitter/src/lib/components/settings-button.tsx
> +        aria-label="settings"
I also didn't notice these mistakes. I will be more careful with code changes going forward.

2024-12-05 06:49 UTC, TakayaShirai approved these changes
LGTM

2024-12-06 09:49 UTC, ryuji0123 approved these changes

2024-12-06 09:50 UTC, merged