[iOS] Implement Swipe and Pan Gesture to Enable Manual Side Menu Transition
okuda-seminar/Twitter-Clone pull request #532
Opened 2024-12-14 09:00 UTC by TakayaShirai

## Issue Number
https://github.com/okuda-seminar/Twitter-Clone/issues/510

## Implementation Summary
This PR introduces a manual side menu transition controlled via a pan gesture.

## Scope of Impact
Users can now open and close the side menu by dragging it with a pan gesture.

## Particular points to check
Please review if the way of introducing the `UIPercentDrivenInteractiveTransition` is appropriate.

## Reference
https://github.com/user-attachments/assets/8018fa33-888e-473a-9b65-5aa0dbee1d29

## Schedule
Until 12/21.

## Note
- In `ScrollView`, users still can't open the side menu by gesture. This issue will be addressed in the https://github.com/okuda-seminar/Twitter-Clone/issues/531. 
- Although the issue and PR title mention a swipe gesture, the implementation uses only a pan gesture because it meets the required functionality without a swipe gesture for now.

2024-12-15 08:09 UTC, a-shigemichi requested changes

2024-12-15 08:09 UTC, a-shigemichi commented on swift/Twitter-iOS/Twitter-iOS/Root/SideMenu/SideMenuTransitionController.swift
> +        let x = gesture.translation(in: gestureView).x
```suggestion
        let horizontalTranslation = gesture.translation(in: gestureView).x
```

2024-12-15 08:21 UTC, a-shigemichi approved these changes
LGTM

2024-12-17 11:15 UTC, ryuji0123 requested changes

2024-12-17 11:15 UTC, ryuji0123 commented on swift/Twitter-iOS/Twitter-iOS/Root/SideMenu/SideMenuTransitionController.swift
> +  public func setUpViewControllersForSideMenuTransition(
Let's start adding comments to your code [ref](https://google.github.io/swift/#documentation-comments).

2024-12-18 06:55 UTC, TakayaShirai commented on swift/Twitter-iOS/Twitter-iOS/Root/SideMenu/SideMenuTransitionController.swift
> +  public func setUpViewControllersForSideMenuTransition(
Although the files I modified in this PR contain other public methods and properties, I chose to add comments only to this function, as the functionalities of the rest seem obvious from their names.

2024-12-19 11:03 UTC, ryuji0123 requested changes

2024-12-19 11:03 UTC, ryuji0123 commented on swift/Twitter-iOS/Twitter-iOS/Root/SideMenu/SideMenuTransitionController.swift
> +  private var parentViewController: UIViewController? = nil
Imagine other engineers sees this file without any comments. Don't you think we need a file comment for explaining general concepts and one per API / prop? You can refer to public API doc like [this](https://cloud.google.com/translate/docs/reference/rest/v3beta1/projects.locations/batchTranslateDocument) to understand how such docs should be organized generally.

2024-12-19 11:03 UTC, ryuji0123 commented on swift/Twitter-iOS/Twitter-iOS/Root/SideMenu/SideMenuTransitionController.swift
> +  private var parentViewController: UIViewController? = nil
If you're preparing for your job hunting, aligning your code with a general standard quality is very important. Otherwise you cannot prove your skill of API docs.

2024-12-20 10:34 UTC, TakayaShirai commented on swift/Twitter-iOS/Twitter-iOS/Root/SideMenu/SideMenuTransitionController.swift
> +  public func setUpViewControllersForSideMenuTransition(
I'll make sure to add comments where the code could be unclear without them moving forward.

2024-12-20 10:35 UTC, TakayaShirai commented on swift/Twitter-iOS/Twitter-iOS/Root/SideMenu/SideMenuTransitionController.swift
> +  private var parentViewController: UIViewController? = nil
Thank you for the suggestions and the reference. I added some comments to the files so I'd appreciate it if you could review them.

2024-12-21 09:35 UTC, ryuji0123 approved these changes
Plz also add comment to MainRootViewController later.

2024-12-21 09:36 UTC, merged