[TS] Refactor Post Display Page to Use Mock Data
okuda-seminar/Twitter-Clone pull request #534
Opened 2024-12-17 05:16 UTC by a-shigemichi

## Issue Number
https://github.com/okuda-seminar/Twitter-Clone/issues/533

## Implementation Summary
Changed post content display in page/[id] to use mock data.

## Particular points to check
Please check if you can see the following error message after clicking the "Post" button by following these steps:

1. Run `docker compose up`.
2. Open `localhost:3000/posts/{any}` .
3. You should see the post detail page.

<img width="1431" alt="スクリーンショット 2024-12-17 14 12 53" src="https://github.com/user-attachments/assets/1a4cdbe9-6a82-4e24-83dd-13e473ab6f44" />

## Test
`ts/twitter/src/app/posts/[id]/__test__/post-detail.spec.tsx`
1. Start the frontend server (in the Twitter-Clone directory)
```
$ docker compose up -d
```
2. Enter the application container and run all test files
```
$ docker compose exec app bash
$ yarn test post-detail.spec.tsx
```
　Use `--coverage` flag to generate coverage report

## Schedule
2024/12/20

2024-12-17 08:56 UTC, TakayaShirai requested changes
I could reproduce the referenced view, but I couldn't understand what "the following error message" mean you mentioned in the "Particular points to check" section. Could you clarify what it means?

Additionally, I encountered an error message in the home view as follows. I guess this is caused by changes on the backend side as I was able to reproduce the error on the main branch as well. Could you add a TODO to address this issue?

![Screenshot 2024-12-17 at 12 11 18 AM (2)](https://github.com/user-attachments/assets/2836dfd7-4716-474a-a930-42105344be6f)


![Screenshot 2024-12-17 at 12 11 30 AM](https://github.com/user-attachments/assets/f119ab9b-d048-424c-90f0-678ec8e99f06)

2024-12-17 08:56 UTC, TakayaShirai commented on ts/twitter/src/app/posts/[id]/__test__/post-detail.spec.tsx
> +  test("Follow button display in initial render", () => {
"display" -> "displays". Also, please add a blank line between each test for better readability.

```suggestion
  test("Rendering PostDetail should success", () => {
    render(<PostDetail />);
  });
  
  test("Follow button displays in initial render", () => {
```

2024-12-17 08:56 UTC, TakayaShirai commented on ts/twitter/src/app/posts/[id]/_components/use-post-detail.ts
> +  const [followDisplayText, setFollowDisplayText] = useState<string>("follow");
"setFollowDisplayText" -> "setFollowButtonText"

```suggestion

export const usePostDetail = (): usePostDetailReturn => {
  const follow = useRef<FollowState>(FollowState.UnFollow);
  const [followDisplayText, setFollowButtonText] = useState<string>("follow");
```

2024-12-17 11:17 UTC, ryuju0911 commented on ts/twitter/src/app/posts/[id]/_components/post-detail.tsx
> +};
You implemented the logic in an unnecessarily complex way.

```suggestion
export const PostDetail = () => {
  const post: Post = mockPostCard;
  const [isFollowing, setIsFollowing] = useState<boolean>(false);
  const toggleFollowStatus = () => setIsFollowing((prev) => !prev);

  return (
    <Box key={post.id} p={8} borderWidth={1} borderRadius="md">
      <Flex>
        <Avatar size="md" name={post.user_id} mr={2} />
        <Text fontWeight="bold" fontSize="xl" mr={4} mt={2}>
          {post.user_id}
        </Text>
        <Button borderRadius="full" onClick={toggleFollowStatus}>
          {/* TODO: https://github.com/okuda-seminar/Twitter-Clone/issues/452 
            - Hide follow button for user's own posts in post detail page. */}
          {isFollowing ? "Following" : "Follow"}
        </Button>
      </Flex>
      <Text mt={10} fontSize="xl">
        {post.text}
      </Text>
    </Box>
  );
};
```

2024-12-18 07:07 UTC, TakayaShirai approved these changes
LGTM

2024-12-18 11:42 UTC, ryuju0911 requested changes

2024-12-18 11:42 UTC, ryuju0911 commented on ts/twitter/src/app/posts/[id]/__test__/post-detail.spec.tsx
> +  test("Follow button displays in initial render", () => {
```suggestion
  test(`"Follow" button displays in initial render`, () => {
```

2024-12-18 11:42 UTC, ryuju0911 commented on ts/twitter/src/app/posts/[id]/__test__/post-detail.spec.tsx
> +  test("Button text changes to following after follow button click", () => {
```suggestion
  test(`Button text changes to "Following" after clicking "Follow" button`, () => {
```

2024-12-18 11:42 UTC, ryuju0911 commented on ts/twitter/src/app/posts/[id]/__test__/post-detail.spec.tsx
> +  test("Button text changes to follow after unfollow action", () => {
```suggestion
  test(`Button text changes to "Follow" after clicking "Following" button`, () => {
```

2024-12-18 11:42 UTC, ryuju0911 commented on ts/twitter/src/app/posts/[id]/mocks/post-card.ts
> +export const mockPostCard: Post = {
nit: It's just a post, not a post card.

2024-12-20 10:31 UTC, ryuju0911 approved these changes
LGTM

2024-12-21 04:23 UTC, ryuji0123 approved these changes
@ryuju0911 You can merge Atsushi's PR without my review unless I explicitly require changes.

2024-12-21 04:23 UTC, merged